spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB  # 限制文件上传的大小
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
fdfs:
  so-timeout: 1501 #读取时间
  connect-timeout: 601 #链接时间
  thumb-image:
    width: 60 #缩略图
    height: 60
  tracker-list: #tracker地址
    - 192.168.25.2:22122
#自定义的属性
ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp