server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/leyou
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.leyou: debug